const translations = {
    tr: {
        title: "FreeDogeAI (FDAI) Ön Satış",
        token_info: "TOKEN BILGILERI",
        token_name: "Token Adı",
        total_supply: "Toplam Arz",
        presale_supply: "Ön Satış Arzı",
        price: "Fiyat",
        bnb_rate: "1 BNB",
        target: "Hedef",
        contract: "Token Kontratı",
        wallet_connect: "CÜZDAN BAĞLANTISI",
        connect_wallet: "Cüzdan Bağla",
        wallet_address: "Cüzdan Adresi",
        bnb_balance: "BNB Bakiyesi",
        select_wallet: "Cüzdan Seç",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "SATIN AL",
        bnb_amount: "BNB Miktarı",
        fdai_amount: "Alınacak FDAI",
        buy: "Satın Al",
        purchased_amount: "Satın Alınan Miktar",
        owned_tokens: "Şahip Olunan Token",
        note: "Klayım işlemlerİ (tokenlerinizin cüzdanlarınızda görünmesi ön satışın tamamlamasının ardından gerçekleşecektir). Süreç, şeffaf ve güvenli bir şekilde yürütülecektir. Daha fazla bilgi için <a href='[iletişim kanalı]' target='_blank'>[iletişim kanalı]</a>.",
        error_connect: "Cüzdan bağlantısı başarısız!",
        install_metamask: "Lütfen Metamask veya başka bir Web3 cüzdanı yükleyin!",
        invalid_amount: "Geçerli bir BNB miktarı girin!",
        success: "Satın alma başarılı! FDAI tokenlar ön satış sonrası cüzdanınıza yansıyacak.",
        error_transaction: "İşlem başarısız"
    },
    en: {
        title: "FreeDogeAI (FDAI) Presale",
        token_info: "TOKEN INFORMATION",
        token_name: "Token Name",
        total_supply: "Total Supply",
        presale_supply: "Presale Supply",
        price: "Price",
        bnb_rate: "1 BNB",
        target: "Target",
        contract: "Token Contract",
        wallet_connect: "WALLET CONNECTION",
        connect_wallet: "Connect Wallet",
        wallet_address: "Wallet Address",
        bnb_balance: "BNB Balance",
        select_wallet: "Select Wallet",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "PURCHASE",
        bnb_amount: "BNB Amount",
        fdai_amount: "FDAI to Receive",
        buy: "Buy",
        purchased_amount: "Purchased Amount",
        owned_tokens: "Owned Tokens",
        note: "Claim transactions (the appearance of your tokens in your wallets will occur after the completion of the presale) will be conducted transparently and securely. For more details, visit <a href='[communication channel]' target='_blank'>[communication channel]</a>.",
        error_connect: "Wallet connection failed!",
        install_metamask: "Please install Metamask or another Web3 wallet!",
        invalid_amount: "Enter a valid BNB amount!",
        success: "Purchase successful! FDAI tokens will be reflected in your wallet after the presale.",
        error_transaction: "Transaction failed"
    },
    ar: {
        title: "FreeDogeAI (FDAI) البيع المسبق",
        token_info: "معلومات التوكن",
        token_name: "اسم التوكن",
        total_supply: "إجمالي العرض",
        presale_supply: "عرض البيع المسبق",
        price: "السعر",
        bnb_rate: "1 BNB",
        target: "الهدف",
        contract: "عقد التوكن",
        wallet_connect: "الاتصال بالمحفظة",
        connect_wallet: "ربط المحفظة",
        wallet_address: "عنوان المحفظة",
        bnb_balance: "رصيد BNB",
        select_wallet: "اختر المحفظة",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "الشراء",
        bnb_amount: "كمية BNB",
        fdai_amount: "FDAI المستلم",
        buy: "شراء",
        purchased_amount: "الكمية المشتراة",
        owned_tokens: "التوكنات المملوكة",
        note: "عمليات المطالبة (ظهور التوكنات في محافظكم سيتم بعد اكتمال البيع المسبق) ستُجرى بطريقة شفافة وآمنة. لمزيد من التفاصيل، تفضلوا بزيارة <a href='[قناة التواصل]' target='_blank'>[قناة التواصل]</a>.",
        error_connect: "فشل الاتصال بالمحفظة!",
        install_metamask: "يرجى تثبيت Metamask أو محفظة Web3 أخرى!",
        invalid_amount: "أدخل كمية BNB صالحة!",
        success: "الشراء ناجح! ستظهر توكنات FDAI في محفظتك بعد البيع المسبق.",
        error_transaction: "فشل المعاملة"
    },
    az: {
        title: "FreeDogeAI (FDAI) İlkin Satış",
        token_info: "TOKEN MƏLUMATLARI",
        token_name: "Token Adı",
        total_supply: "Ümumi Təklif",
        presale_supply: "İlkin Satış Təklifi",
        price: "Qiymət",
        bnb_rate: "1 BNB",
        target: "Hədəf",
        contract: "Token Müqaviləsi",
        wallet_connect: "CÜZDAN BAĞLANTISI",
        connect_wallet: "Cüzdanı Bağla",
        wallet_address: "Cüzdan Ünvanı",
        bnb_balance: "BNB Balansı",
        select_wallet: "Cüzdan Seç",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "ALIN",
        bnb_amount: "BNB Miqdarı",
        fdai_amount: "Alınacaq FDAI",
        buy: "Al",
        purchased_amount: "Alınmış Miqdar",
        owned_tokens: "Şahib Olunan Token",
        note: "Klaym əməliyyatları (tokenlərinizin cüzdanlarınızda görünməsi ilkin satışın tamamlanmasından sonra baş verəcək). Proses şəffaf və təhlükəsiz şəkildə həyata keçiriləcək. Ətraflı məlumat üçün <a href='[əlaqə kanalı]' target='_blank'>[əlaqə kanalı]</a>.",
        error_connect: "Cüzdan bağlantısı uğursuz oldu!",
        install_metamask: "Zəhmət olmasa Metamask və ya başqa bir Web3 cüzdanı quraşdırın!",
        invalid_amount: "Etibarlı BNB miqdarı daxil edin!",
        success: "Alış uğurlu oldu! FDAI tokenləri ilkin satışdan sonra cüzdanınızda görünəcək.",
        error_transaction: "Əməliyyat uğursuz oldu"
    },
    ru: {
        title: "FreeDogeAI (FDAI) Предпродажа",
        token_info: "ИНФОРМАЦИЯ О ТОКЕНЕ",
        token_name: "Название токена",
        total_supply: "Общий объем",
        presale_supply: "Объем предпродажи",
        price: "Цена",
        bnb_rate: "1 BNB",
        target: "Цель",
        contract: "Контракт токена",
        wallet_connect: "ПОДКЛЮЧЕНИЕ КОШЕЛЬКА",
        connect_wallet: "Подключить кошелек",
        wallet_address: "Адрес кошелька",
        bnb_balance: "Баланс BNB",
        select_wallet: "Выберите кошелек",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "ПОКУПКА",
        bnb_amount: "Количество BNB",
        fdai_amount: "Получаемые FDAI",
        buy: "Купить",
        purchased_amount: "Купленное количество",
        owned_tokens: "Ваши токены",
        note: "Операции по клейму (появление ваших токенов в кошельках произойдет после завершения предпродажи) будут проводиться прозрачно и безопасно. Подробности на <a href='[канал связи]' target='_blank'>[канал связи]</a>.",
        error_connect: "Ошибка подключения кошелька!",
        install_metamask: "Пожалуйста, установите Metamask или другой кошелек Web3!",
        invalid_amount: "Введите действительное количество BNB!",
        success: "Покупка успешна! Токены FDAI появятся в вашем кошельке после предпродажи.",
        error_transaction: "Ошибка транзакции"
    },
    zh: {
        title: "FreeDogeAI (FDAI) 预售",
        token_info: "代币信息",
        token_name: "代币名称",
        total_supply: "总供应量",
        presale_supply: "预售供应量",
        price: "价格",
        bnb_rate: "1 BNB",
        target: "目标",
        contract: "代币合约",
        wallet_connect: "钱包连接",
        connect_wallet: "连接钱包",
        wallet_address: "钱包地址",
        bnb_balance: "BNB余额",
        select_wallet: "选择钱包",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "购买",
        bnb_amount: "BNB数量",
        fdai_amount: "将获得的FDAI",
        buy: "购买",
        purchased_amount: "已购买数量",
        owned_tokens: "拥有的代币",
        note: "领取操作（您的代币将在预售结束后出现在您的钱包中）将以透明和安全的方式进行。详情请访问 <a href='[通信渠道]' target='_blank'>[通信渠道]</a>。",
        error_connect: "钱包连接失败！",
        install_metamask: "请安装Metamask或其他Web3钱包！",
        invalid_amount: "请输入有效的BNB数量！",
        success: "购买成功！FDAI代币将在预售后反映在您的钱包中。",
        error_transaction: "交易失败"
    },
    ja: {
        title: "FreeDogeAI (FDAI) プレセール",
        token_info: "トークン情報",
        token_name: "トークン名",
        total_supply: "総供給量",
        presale_supply: "プレセール供給量",
        price: "価格",
        bnb_rate: "1 BNB",
        target: "目標",
        contract: "トークンコントラクト",
        wallet_connect: "ウォレット接続",
        connect_wallet: "ウォレットを接続",
        wallet_address: "ウォレットアドレス",
        bnb_balance: "BNB残高",
        select_wallet: "ウォレットを選択",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "購入",
        bnb_amount: "BNB数量",
        fdai_amount: "受け取るFDAI",
        buy: "購入",
        purchased_amount: "購入済み数量",
        owned_tokens: "所有トークン",
        note: "クレーム取引（トークンがウォレットに表示されるのはプレセール完了後です）は透明かつ安全に実施されます。詳細は <a href='[通信チャネル]' target='_blank'>[通信チャネル]</a> をご覧ください。",
        error_connect: "ウォレット接続に失敗しました！",
        install_metamask: "Metamaskまたは他のWeb3ウォレットをインストールしてください！",
        invalid_amount: "有効なBNB数量を入力してください！",
        success: "購入成功！FDAIトークンはプレセール後にウォレットに反映されます。",
        error_transaction: "取引に失敗しました"
    },
    ur: {
        title: "FreeDogeAI (FDAI) پری سیل",
        token_info: "ٹوکن کی معلومات",
        token_name: "ٹوکن کا نام",
        total_supply: "کل سپلائی",
        presale_supply: "پری سیل سپلائی",
        price: "قیمت",
        bnb_rate: "1 BNB",
        target: "ہدف",
        contract: "ٹوکن کنٹریکٹ",
        wallet_connect: "والیٹ کنکشن",
        connect_wallet: "والیٹ جوڑیں",
        wallet_address: "والیٹ ایڈریس",
        bnb_balance: "BNB بیلنس",
        select_wallet: "والیٹ منتخب کریں",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "خریداری",
        bnb_amount: "BNB کی مقدار",
        fdai_amount: "وصول ہونے والا FDAI",
        buy: "خریدیں",
        purchased_amount: "خریداری کی گئی مقدار",
        owned_tokens: "آپ کے ٹوکنز",
        note: "دعویٰ کے لین دین (آپ کے ٹوکنز کا آپ کے والیٹس میں ظاہر ہونا پری سیل کے مکمل ہونے کے بعد ہوگا) شفاف اور محفوظ طریقے سے انجام دیا جائے گا۔ مزید تفصیلات کے لیے <a href='[رابطہ چینل]' target='_blank'>[رابطہ چینل]</a> پر جائیں۔",
        error_connect: "والیٹ کنکشن ناکام ہوا!",
        install_metamask: "براہ کرم Metamask یا کوئی اور Web3 والیٹ انسٹال کریں!",
        invalid_amount: "درست BNB مقدار درج کریں!",
        success: "خریداری کامیاب! FDAI ٹوکنز پری سیل کے بعد آپ کے والیٹ میں ظاہر ہوں گے۔",
        error_transaction: "لین دین ناکام ہوا"
    },
    hi: {
        title: "FreeDogeAI (FDAI) प्रीसेल",
        token_info: "टोकन जानकारी",
        token_name: "टोकन का नाम",
        total_supply: "कुल आपूर्ति",
        presale_supply: "प्रीसेल आपूर्ति",
        price: "मूल्य",
        bnb_rate: "1 BNB",
        target: "लक्ष्य",
        contract: "टोकन अनुबंध",
        wallet_connect: "वॉलेट कनेक्शन",
        connect_wallet: "वॉलेट कनेक्ट करें",
        wallet_address: "वॉलेट पता",
        bnb_balance: "BNB शेष",
        select_wallet: "वॉलेट चुनें",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        purchase: "खरीदारी",
        bnb_amount: "BNB राशि",
        fdai_amount: "प्राप्त होने वाला FDAI",
        buy: "खरीदें",
        purchased_amount: "खरीदी गई राशि",
        owned_tokens: "आपके टोकन",
        note: "दावा लेनदेन (आपके टोकन आपके वॉलेट में प्रीसेल पूरा होने के बाद दिखाई देंगे) पारदर्शी और सुरक्षित रूप से आयोजित किए जाएंगे। अधिक जानकारी के लिए <a href='[संचार चैनल]' target='_blank'>[संचार चैनल]</a> पर जाएं।",
        error_connect: "वॉलेट कनेक्शन विफल!",
        install_metamask: "कृपया Metamask या कोई अन्य Web3 वॉलेट स्थापित करें!",
        invalid_amount: "मान्य BNB राशि दर्ज करें!",
        success: "खरीदारी सफल! FDAI टोकन प्रीसेल के बाद आपके वॉलेट में दिखाई देंगे।",
        error_transaction: "लेनदेन विफल"
    }
};

function changeLang(lang) {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (element.tagName === 'P' && key === 'note') {
            element.innerHTML = translations[lang][key];
        } else {
            element.textContent = translations[lang][key] || element.textContent;
        }
    });
    document.documentElement.lang = lang;
    localStorage.setItem('lang', lang);
}

window.addEventListener('load', () => {
    const savedLang = localStorage.getItem('lang') || 'tr';
    changeLang(savedLang);
    document.querySelector('.lang-toggle select').value = savedLang;
});
