const translations = {
    tr: {
        title: "FreeDogeAI (FDAI) Ön Satış",
        token_info: "Token Bilgileri",
        token_name: "Token Adı",
        total_supply: "Toplam Arz",
        presale_supply: "Ön Satış Arzı",
        price: "Fiyat",
        bnb_rate: "1 BNB",
        target: "Hedef",
        contract: "Token Kontratı",
        wallet_connect: "Cüzdan Bağlantısı",
        connect_wallet: "Cüzdanı Bağla",
        wallet_address: "Cüzdan Adresi",
        bnb_balance: "BNB Bakiyesi",
        purchase: "Satın Al",
        bnb_amount: "BNB Miktarı",
        fdai_amount: "Alınacak FDAI",
        buy: "Satın Al",
        purchased_amount: "Satın Alınan Miktar",
        owned_tokens: "Sahip Olunan Token",
        note: "Klayım işlemleri (tokenlerinizin cüzdanlarınızda görünmesi ön satışın tamamlanmasının ardından gerçekleşecektir). Süreç, şeffaf ve güvenli bir şekilde yürütülecektir. Daha fazla bilgi için [iletişim kanalı].",
        select_wallet: "Cüzdan Seç",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        close: "Kapat"
    },
    en: {
        title: "FreeDogeAI (FDAI) Presale",
        token_info: "Token Information",
        token_name: "Token Name",
        total_supply: "Total Supply",
        presale_supply: "Presale Supply",
        price: "Price",
        bnb_rate: "1 BNB",
        target: "Target",
        contract: "Token Contract",
        wallet_connect: "Wallet Connection",
        connect_wallet: "Connect Wallet",
        wallet_address: "Wallet Address",
        bnb_balance: "BNB Balance",
        purchase: "Purchase",
        bnb_amount: "BNB Amount",
        fdai_amount: "FDAI to Receive",
        buy: "Buy",
        purchased_amount: "Purchased Amount",
        owned_tokens: "Owned Tokens",
        note: "Claim transactions (the appearance of your tokens in your wallets will occur after the completion of the presale) will be conducted transparently and securely. For more details, visit [communication channel].",
        select_wallet: "Select Wallet",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        close: "Close"
    },
    ar: {
        title: "FreeDogeAI (FDAI) البيع المسبق",
        token_info: "معلومات التوكن",
        token_name: "اسم التوكن",
        total_supply: "إجمالي العرض",
        presale_supply: "عرض البيع المسبق",
        price: "السعر",
        bnb_rate: "1 BNB",
        target: "الهدف",
        contract: "عقد التوكن",
        wallet_connect: "الاتصال بالمحفظة",
        connect_wallet: "ربط المحفظة",
        wallet_address: "عنوان المحفظة",
        bnb_balance: "رصيد BNB",
        purchase: "الشراء",
        bnb_amount: "كمية BNB",
        fdai_amount: "FDAI المستلم",
        buy: "شراء",
        purchased_amount: "الكمية المشتراة",
        owned_tokens: "التوكنات المملوكة",
        note: "عمليات المطالبة (ظهور التوكنات في محافظكم سيتم بعد اكتمال البيع المسبق) ستُجرى بطريقة شفافة وآمنة. لمزيد من التفاصيل، تفضلوا بزيارة [قناة التواصل].",
        select_wallet: "اختر المحفظة",
        metamask: "Metamask",
        wallet_connect_option: "WalletConnect",
        trust_wallet: "Trust Wallet",
        close: "إغلاق"
    },
    // Diğer diller (az, ru, zh, ja, ur, hi) için çeviriler eklenecek, GitHub’da tam sürüm olacak.
};

function changeLang(lang) {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        element.textContent = translations[lang][key] || element.textContent;
    });
    document.documentElement.lang = lang;
}
