const translations = {
    en: {
        presale_title: "Presale Ends Soon",
        presale_desc: "Don't miss your chance to join FreeDogeAI! Buy FDAI tokens now.",
        connect_wallet: "Connect Wallet",
        wallet_address: "Wallet Address",
        bnb_balance: "BNB Balance",
        purchased_amount: "Purchased FDAI",
        select_wallet: "Select Wallet",
        metamask: "MetaMask",
        trust_wallet: "Trust Wallet",
        close: "Close",
        buy_tokens: "Buy FDAI Tokens",
        bnb_amount: "Enter BNB Amount",
        receive_fdai: "You will receive",
        your_tokens: "Your Tokens",
        you_own: "You Own",
        token_note: "Your tokens will be reflected in your wallet after the presale ends.",
        whitepaper: "Whitepaper",
        download_whitepaper: "Download Whitepaper",
        community: "Join Our Community",
        community_desc: "Stay updated and connected with the FreeDogeAI community",
        telegram: "Telegram",
        twitter: "Twitter",
        error_connect: "Wallet connection failed!",
        install_metamask: "Please install MetaMask or another Web3 wallet!",
        invalid_amount: "Enter a valid BNB amount!",
        success: "Purchase successful! FDAI tokens will be reflected in your wallet after the presale.",
        error_transaction: "Transaction failed"
    },
    tr: {
        presale_title: "Ön Satış Yakında Bitiyor",
        presale_desc: "FreeDogeAI'a katılma şansınızı kaçırmayın! FDAI tokenlarını şimdi satın alın.",
        connect_wallet: "Cüzdanı Bağla",
        wallet_address: "Cüzdan Adresi",
        bnb_balance: "BNB Bakiyesi",
        purchased_amount: "Satın Alınan FDAI",
        select_wallet: "Cüzdan Seç",
        metamask: "MetaMask",
        trust_wallet: "Trust Wallet",
        close: "Kapat",
        buy_tokens: "FDAI Token Satın Al",
        bnb_amount: "BNB Miktarı Girin",
        receive_fdai: "Alacağınız miktar",
        your_tokens: "Tokenlarınız",
        you_own: "Sahip Olduğunuz",
        token_note: "Tokenlarınız ön satış sona erdikten sonra cüzdanınıza yansıyacaktır.",
        whitepaper: "Beyaz Kitap",
        download_whitepaper: "Beyaz Kitabı İndir",
        community: "Topluluğumuza Katılın",
        community_desc: "FreeDogeAI topluluğu ile güncel kalın ve bağlantıda olun",
        telegram: "Telegram",
        twitter: "Twitter",
        error_connect: "Cüzdan bağlantısı başarısız!",
        install_metamask: "Lütfen MetaMask veya başka bir Web3 cüzdanı yükleyin!",
        invalid_amount: "Geçerli bir BNB miktarı girin!",
        success: "Satın alma başarılı! FDAI tokenlar ön satış sonrası cüzdanınıza yansıyacak.",
        error_transaction: "İşlem başarısız"
    },
    ja: {
        presale_title: "プレセールが間もなく終了します",
        presale_desc: "FreeDogeAIに参加するチャンスを逃さないで！今すぐFDAIトークンを購入してください。",
        connect_wallet: "ウォレットを接続",
        wallet_address: "ウォレットアドレス",
        bnb_balance: "BNB残高",
        purchased_amount: "購入済みFDAI",
        select_wallet: "ウォレットを選択",
        metamask: "MetaMask",
        trust_wallet: "Trust Wallet",
        close: "閉じる",
        buy_tokens: "FDAIトークンを購入",
        bnb_amount: "BNB数量を入力",
        receive_fdai: "受け取るFDAI",
        your_tokens: "あなたのトークン",
        you_own: "所有トークン",
        token_note: "トークンはプレセール終了後にウォレットに反映されます。",
        whitepaper: "ホワイトペーパー",
        download_whitepaper: "ホワイトペーパーをダウンロード",
        community: "コミュニティに参加",
        community_desc: "FreeDogeAIコミュニティで最新情報を入手し、つながりを保ちましょう",
        telegram: "Telegram",
        twitter: "Twitter",
        error_connect: "ウォレット接続に失敗しました！",
        install_metamask: "MetaMaskまたは他のWeb3ウォレットをインストールしてください！",
        invalid_amount: "有効なBNB数量を入力してください！",
        success: "購入成功！FDAIトークンはプレセール後にウォレットに反映されます。",
        error_transaction: "取引に失敗しました"
    },
    zh: {
        presale_title: "预售即将结束",
        presale_desc: "不要错过加入FreeDogeAI的机会！现在购买FDAI代币。",
        connect_wallet: "连接钱包",
        wallet_address: "钱包地址",
        bnb_balance: "BNB余额",
        purchased_amount: "已购买FDAI",
        select_wallet: "选择钱包",
        metamask: "MetaMask",
        trust_wallet: "Trust Wallet",
        close: "关闭",
        buy_tokens: "购买FDAI代币",
        bnb_amount: "输入BNB数量",
        receive_fdai: "您将收到",
        your_tokens: "您的代币",
        you_own: "您拥有",
        token_note: "您的代币将在预售结束后反映在您的钱包中。",
        whitepaper: "白皮书",
        download_whitepaper: "下载白皮书",
        community: "加入我们的社区",
        community_desc: "与FreeDogeAI社区保持更新和联系",
        telegram: "Telegram",
        twitter: "Twitter",
        error_connect: "钱包连接失败！",
        install_metamask: "请安装MetaMask或其他Web3钱包！",
        invalid_amount: "请输入有效的BNB数量！",
        success: "购买成功！FDAI代币将在预售后反映在您的钱包中。",
        error_transaction: "交易失败"
    },
    ru: {
        presale_title: "Предпродажа скоро закончится",
        presale_desc: "Не упустите шанс присоединиться к FreeDogeAI! Покупайте токены FDAI прямо сейчас.",
        connect_wallet: "Подключить кошелек",
        wallet_address: "Адрес кошелька",
        bnb_balance: "Баланс BNB",
        purchased_amount: "Купленные FDAI",
        select_wallet: "Выберите кошелек",
        metamask: "MetaMask",
        trust_wallet: "Trust Wallet",
        close: "Закрыть",
        buy_tokens: "Купить токены FDAI",
        bnb_amount: "Введите сумму BNB",
        receive_fdai: "Вы получите",
        your_tokens: "Ваши токены",
        you_own: "У вас есть",
        token_note: "Ваши токены будут отражены в вашем кошельке после окончания предпродажи.",
        whitepaper: "Белая книга",
        download_whitepaper: "Скачать белую книгу",
        community: "Присоединяйтесь к нашему сообществу",
        community_desc: "Оставайтесь в курсе и на связи с сообществом FreeDogeAI",
        telegram: "Telegram",
        twitter: "Twitter",
        error_connect: "Ошибка подключения кошелька!",
        install_metamask: "Пожалуйста, установите MetaMask или другой кошелек Web3!",
        invalid_amount: "Введите действительное количество BNB!",
        success: "Покупка успешна! Токены FDAI появятся в вашем кошельке после предпродажи.",
        error_transaction: "Ошибка транзакции"
    }
};

function changeLang(lang) {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        element.textContent = translations[lang][key] || element.textContent;
    });
    document.documentElement.lang = lang;
    localStorage.setItem('lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'en';
    changeLang(savedLang);
    document.getElementById('langSelect').value = savedLang;
});
